version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librariesio
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - librariesio
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/librariesio?sslmode=disable
    networks:
      - librariesio
    depends_on:
      - postgres
  librariesio:
    container_name: librariesio
    image: librariesio:latest
    build:
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: $LIBIO_HOME
        target: /data
    networks:
      - librariesio
    depends_on:
      - postgres
volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/db/libio
networks:
  librariesio:
    name: "librariesio"
